import { connectToMongoDB } from "@/lib/db";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  connectToMongoDB();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
