<<<<<<< HEAD
import { connectToMongoDB } from "@/lib/db";
import "./globals.css";
=======
import "./globals.css";

>>>>>>> e6e4129 (price detail)
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
<<<<<<< HEAD
  connectToMongoDB();
=======
>>>>>>> e6e4129 (price detail)
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
