export const Provinces = [
  { name: "Архангай", type: "chuluutin havtsal" },
  { name: "Баян-Өлгий	", type: "kazah  Salem aleukum" },
  { name: "Баянхонгор	", type: "mogoi" },
  { name: "Булган", type: "shiiwgai" },
  { name: "Говь-Алтай", type: "shoklad" },
  { name: "	Говьсүмбэр", type: "daagii" },
  { name: "Дархан-Уул", type: "tovdoo" },
  { name: "Дорноговь", type: "hangai sayaanii" },
  { name: "Дорнод", type: "Nuur" },
  { name: "Дундговь", type: "UB" },
  { name: "Завхан", type: "hoshoo" },
  { name: "Орхон", type: "Dorno-gobi simba" },
  { name: "	Өвөрхангай", type: "Tom chuluu" },
  { name: "	Өмнөговь", type: "Ulni aimag" },
  { name: "Сүхбаатар", type: "zaa ter us mus" },
  { name: "Сэлэнгэ", type: "ingenii hoormog" },
  { name: "Төв", type: "Manai geriig sonirhooroi" },
  { name: "Увс", type: "Airag ayayay" },
  { name: "Ховд", type: "ingenii hoormog" },
  { name: "Хөвсгөл", type: "Manai geriig sonirhooroi" },
  { name: "Хэнтий", type: "Airag ayayay" },
];
