export const Provinces = [
  { name: "Arhangai", type: "chuluutin havtsal" },
  { name: "Bayn-Olgii", type: "kazah  Salem aleukum" },
  { name: "Baynkhongor", type: "mogoi" },
  { name: "Bulgan", type: "shiiwgai" },
  { name: "Gobi-Altai", type: "shoklad" },
  { name: "Darkhan-uul", type: "daagii" },
  { name: "Tov", type: "tovdoo" },
  { name: "Khentii", type: "hangai sayaanii" },
  { name: "Uvs", type: "Nuur" },
  { name: "Ulaanbaatar", type: "UB" },
  { name: "Sukhbaatar", type: "hoshoo" },
  { name: "Dorno-gobi", type: "Dorno-gobi simba" },
  { name: "Ovorhangai", type: "Tom chuluu" },
  { name: "Zavhan", type: "Ulni aimag" },
  { name: "Khuvsgul", type: "zaa ter us mus" },
  { name: "Omno-gobi", type: "ingenii hoormog" },
  { name: "Bagannur", type: "Manai geriig sonirhooroi" },
  { name: "Selenge", type: "Airag ayayay" },
];
